### ISSUE TITLE
Multi Query Single Transaction

### ISSUE THREAD

**Issue by jzumbrun** [vlucas/spot2#116]
Is there a way to create a single transaction with multiple queries like doctrine allows with `->flush()`?

I would like to create a single transaction for multi inserts.

**Comment by Mashkin** [comment]
You can use `Mapper::transaction()` to perform a transaction with rollback support (if the RDBMS supports it):

An example:

    $mapper = $locator->mapper('Entity\ClassName');
    $mapper->transaction(function($mapper) { 
        $entity1 = $mapper->create($data1);
        $entity2 = $mapper->create($data2);
        return array($entity1, $entity2)
    });

Unfortunately, the transaction feature lacks documentation. But you can read the code [here](https://github.com/vlucas/spot2/blob/master/lib/Mapper.php#L952).

The transaction will be rolled back if the callable returns false or an exception is thrown

**Comment by jzumbrun** [comment]
Very cool. Thanks. I like it.

**Comment by jzumbrun** [comment]
Just wanted to comment that before I used the traction method it took like 7 minutes for SQLite to insert 2000 records. The transaction method brought that down to less than 7 seconds! SWEET!

**Comment by vlucas** [comment]
Awesome! a 60x speed increase! :+1:
