### ISSUE TITLE
Object and array types not modified

### ISSUE THREAD

**Issue by willemwollebrants** [vlucas/spot2#121]
When updating an array  (or object) field like this:
$entity->params['foo'] = 'bar';
the change is not detected by the entity. This is perfectly logical because the setter is never called (we're updating a reference). The correct value is stored in Entity::$_data, but not in Entity::$_dataModified. 

This screws up the output for Entity::dataModified() and Entity::dataUnmodified(), and it's a problem when you're trying to save the object, because saving/updating will only look at the modified fields.

This fixes saving by the way :)
$entity->params['foo'] = 'bar';
$entity->params= $entity->params;

**Comment by vlucas** [comment]
Seems like a bug. I will investigate.
