### ISSUE TITLE
Add to Collection able to be serialized for json_encode()

### ISSUE THREAD

**Issue by NekaKawaii** [vlucas/spot2#122]
When I try to convert filled `Spot\Collection` to json string, I've got emty json object "{}"
``` 
$tokens = $mapper->all()->where(["user_id" => $userInfo["user_id"]])
                ->execute();
$jsonString = json_encode($tokens);
```

Please, implement `Spot\Collection::jsonSerialize()`, and make it using `Spot\Entity` child's custom `jsonSerialize()` if any.

**Comment by vlucas** [comment]
This is a pretty good idea. So basically, just make it work the same as `toArray` currently does with collections and entities?

**Comment by NekaKawaii** [comment]
Exactly. Now I need to call `json_encode($collection->toArray())` which will be call `EntityClild::toArray()` on each, but using `jsonSerializable` interface for `Collection` would be more natural, like `json_encode($collection)`. So `Collection::jsonSerialize()` should use `Etity::jsonSerialize()` under the hood. Not `Entity::toArray()` like now, because it takes some time to dig in and point it out.
