### ISSUE TITLE
Table aliases

### ISSUE THREAD

**Issue by Dijky** [vlucas/spot2#126]
When generating the SQL statement for a query, an alias equal to the table name is set for tables - e.g.:

    SELECT * FROM `tickets` `tickets` 
    WHERE `tickets`.`creator_id` IS NULL
    ORDER BY `tickets`.`date_created` DESC

This happens here: https://github.com/vlucas/spot2/blob/master/lib/Mapper.php#L641

What is the purpose of setting this alias?  
If the alias was _not_ set, one could specify the database name in an entity:

    protected static $table = 'support.tickets';

Which expands to this SQL statement:

    SELECT * FROM `support`.`tickets` `support`.`tickets` 
    WHERE `support`.`tickets`.`creator_id` IS NULL
    ORDER BY `support`.`tickets`.`date_created` DESC

This table alias obviously causes a syntax error.

So leaving out the alias entirely would yield a correct and valid statement.

Please post your feedback for this change.

I will provide a pull request shortly.

**Comment by vlucas** [comment]
This is fixed by merging in #127
