### ISSUE TITLE
$cfg->addConnection unfriendly for DI containers like Aura DI 3.x

### ISSUE THREAD

**Issue by acim** [vlucas/spot2#128]
This is a great container but allows just one argument per parameter, meaning this mysql or whatever should go inside the array and addConnection should accept just an array. Of course, for compatibility reasons this form should also be kept, but we should allow just one array as an argument.

```
$cfg->addConnection('mysql', [
    'dbname' => 'mydb',
    'user' => 'user',
    'password' => 'secret',
    'host' => 'localhost',
    'driver' => 'pdo_mysql',
]);
```

becomes like:

```
$cfg->addConnection([
    'name' => 'mysql',
    'dbname' => 'mydb',
    'user' => 'user',
    'password' => 'secret',
    'host' => 'localhost',
    'driver' => 'pdo_mysql',
]);
```

and the contract should be like:

```
/**
* $name string|array
*/
public function addConnection($name, $dsn = null, $default = false) {}
```

In the future releases it should probably loose the other parameters and keep just the array (debatable).

**Comment by vlucas** [comment]
I am pretty sure Aura.DI can handle method signatures with multiple parameters, and can support configuring Spot database connections as-is. Can you shed some light here, @pmjones?

**Comment by acim** [comment]
Yes, some light here would be nice :) Sorry for posting this here, it is not related with Spot, but here is what I have tried:

```
<?php
use Aura\Di\ContainerBuilder;

require_once dirname(__DIR__) . '/vendor/autoload.php';

class Test
{
    public function setMe($param1, $param2)
    {
        echo "$param1 $param2";
    }
}

$builder = new ContainerBuilder();
$di = $builder->newInstance();
$di->setters['Test']['setMe'] = ['param1' => 1, 'param2' => 2];
$di->set('test', $di->newInstance('Test'));

$test = $di->get('test');

$di->setters['Test']['setMe']['param1'] = 1;
$di->setters['Test']['setMe']['param2'] = 2;
$di->set('test2', $di->newInstance('Test'));

$test2 = $di->get('test2');
```

**Comment by silentworks** [comment]
You should be able to do it on of these two ways:

This one is untested:

```php
<?php
$di->set('config', $di->lazyNew('\Spot\Config',
    [],
    [
        'addConnection' => [
            'name' => 'mysql',
            'dsn' => [
                'dbname' => 'mydb',
                'user' => 'user',
                'password' => 'secret',
                'host' => 'localhost',
                'driver' => 'pdo_mysql',
            ]
        ]
    ]
));

$di->set('db', $di->lazyNew('\Spot\Locator', [
    'config' => $di->lazyGet('config')
]));
```

This one is tested:

```php
$di->set('db', $di->lazy(function () {
    $cfg = new \Spot\Config();
    $cfg->addConnection('mysql', [
        'dbname' => 'mydb',
        'user' => 'user',
        'password' => 'secret',
        'host' => 'localhost',
        'driver' => 'pdo_mysql',
    ]);
    return new \Spot\Locator($cfg);
}));
```

**Comment by acim** [comment]
The first way sounds interesting, I will try it tonight.

But the second one is really just normal instantiating the Config object, although lazy load feature from the container has been used. I mean this is not bad, but nor as elegant as $di->setters.

I still think $di->setters should support more arguments, just like $di->params does.

**Comment by vlucas** [comment]
Thanks @silentworks. I am closing this issue since this is not a problem with Spot.

**Comment by acim** [comment]
Just to note, maybe someone else will have the same doubt. The first way from @silentworks does not work and triggers the same error as the setters array:

````
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Missing argument 2 for Spot\Config::addConnection(), called in /media/xxx/vendor/aura/di/src/Injection/Factory.php on line 109 and defined' in /media/xxx/vendor/vlucas/spot2/lib/Config.php:24
```

The second way works, although it is just a hack. The only modification I did is to actually use anonymous to create a Config instance and not the Locator instance. So, something like:

```
use Spot\Config as SpotConfig;
use Spot\Locator;

        $di->set('spot_config', $di->lazy(function () use ($dbConfig) {
            $spotConfig = new SpotConfig();
            $spotConfig->addConnection('mysql', $dbConfig, true);
            return $spotConfig;
        }));
        $di->params[Locator::class]['config'] = $di->get('spot_config');
        $di->set('spot_orm', $di->lazyNew(Locator::class));
```

**Comment by silentworks** [comment]
This is not a hack, it is actually recommended to do it this way if you cannot do it using any of the built in lazy* functions.

http://auraphp.com/packages/Aura.Di/lazy.html#1.6.5

**Comment by acim** [comment]
Sorry for my English, I wanted to say a surrogate actually. Don't you think there should be a clean way?

**Comment by vlucas** [comment]
There is nothing inherently wrong with a method signature having a string as the first parameter, and an array as the second. There is no issue here that requires any changes in Spot, and certainly not one that causes backwards compatibility breakages in future releases. I am not changing this method signature.

**Comment by acim** [comment]
No Vance, I am not saying that you should change anything. This is obviously a problem of Aura, sorry for the inconvenience 😉 The problem is that there is no response from their side, but that's OK also, we are part of the OpenSouce comunnity anyway. Thank you for your great work, I like Spot very much and I am going to continue using it and try to help as much as I can.

**Comment by vlucas** [comment]
@acim I see. If that is the case, then I recommend you open a ticket/issue record in the Aura.DI project so you can bring it to their attention a bit better. You are likely to get a lot more help with the DI container there since it's their own project :)

**Comment by acim** [comment]
I did that quite some time ago (before here) ;)
