### ISSUE TITLE
Setting a relation fails after insert

### ISSUE THREAD

**Issue by nebulousGirl** [vlucas/spot2#131]
I have encountered a weird bug which results in inconsistent behavior:

```php
//If set before insertion
$entity->set('relation', /*Array of entities*/);
$entity->get('relation'); //Returns array

$mapper->insert($entity);

//If set after insertion
$entity2->set('relation', /*Array of entities*/);
$entity2->get('relation'); //Returns null
```

After the first entity is inserted in database, the setter does not work anymore.

Any idea on why this happens?

**Comment by nebulousGirl** [comment]
If I use an arbitrary value which is not a relation name, it works.

**Comment by vlucas** [comment]
Spot does not automatically save related entities at this time - is that what you are trying to accomplish here?

Explanation:
I think what is going on for the second attempt after insertion is that Spot reloads entity relations after save, which probably clears your property.

Also - If you want to explicitly set a relation in Spot, you have to use the `relation` method instead:

```php
$entity->relation('posts', [ /* array of entities, or ideally a Spot\Entity\Collection object */]);
```

The `get` and `set` methods are for properties, so they will not work reliably for relations.

**Comment by nebulousGirl** [comment]
I know about the `relation` method, and when digging into the code I saw that `set` uses `relation` when you try to set a relation. So, I don't think that's the problem here. 

I also know that Spot does not save relations which is what I am trying to implement right now.

I created in my mapper a `saveRelations` method. The problem is that I get inconsistent results when setting explicit relations.

In my example above, I work on the first entity without any problems. The explicit relation is working like expected and I can use `$entity->get('relationName')`

But, after inserting my first entity, I cannot seem to be able to set an explicit relation on **other entities** which have not been inserted yet, it always returns `null`.

**Comment by nebulousGirl** [comment]
I just tried using `relation` directly and it works as expected.

It seems like there is something wrong with this variable `self::$relationFields[get_class($this)]` in the `get` and `set` which makes retrieving and setting relation unreliable.

I think either `relation` should be removed from `get` and `set` or `self::$relationFields` should be fixed to be more reliable in `get` and `set`.

The problem lies in Entity::set, line 482:

```php
        if (in_array($field, self::$relationFields[get_class($this)])) {
            // Set relation
            $this->relation($field, $value);
        } elseif ($modified) {
            $this->_dataModified[$field] = $value;
        } else {
            $this->_data[$field] = $value;
        }
```

**Comment by nebulousGirl** [comment]
I just realized I had a property of the same name as my relation. So, I think I encountered an edge case where `get` and `set` don't set/get data in the same place.

`set` goes in this order: relation, dataModified, then data.
`get` goes in this order: dataModified, data, then relation.

We might just need to reorder them so that they match each other.
