### ISSUE TITLE
[QUESTION] Does Spot support TRANSACTION?

### ISSUE THREAD

**Issue by redstrike** [vlucas/spot2#140]
I need to use TRANSACTION to ensure that an entity was correctly created because I have split its data into 2 tables. Does Spot support TRANSACTION or I have to create a custom query?

**Comment by nebulousGirl** [comment]
It it not present in the docs, but you can find it in the [Mapper](https://github.com/vlucas/spot2/blob/master/lib/Mapper.php#L953) class. 

How to use it:
```php
$mapper->transaction(function($mapper) {
    //Inside the transaction
    //Returning false or throwing an exception will rollback the transaction
});
```

**Comment by Dijky** [comment]
Possible duplicate of issue #116

**Comment by redstrike** [comment]
Thank you. I didn't see any mention about it in the docs so I reach here.
