### ISSUE TITLE
Entity still modified after save

### ISSUE THREAD

**Issue by nebulousGirl** [vlucas/spot2#141]
I think the entity shouldn't be still marked as modified after having been persisted to the database.

```php
$entity = $mapper->get(1);
$entity->name = 'Test';
$mapper->save($entity);
$entity->isModified(); //returns true
$entity->isModified('name'); //returns true
```

**Comment by nebulousGirl** [comment]
This line needs to be added to the `update` method, and maybe the insert method too, in the mapper:

```
$entity->data($entity->data(), false);
````

**Comment by vlucas** [comment]
I agree. This is a bug that needs to be fixed.

**Comment by nebulousGirl** [comment]
See pull request #142
