### ISSUE TITLE
Why are fields defined in entities?

### ISSUE THREAD

**Issue by whatda** [vlucas/spot2#146]
Hi,

I think your mapper looks really good, but there's one thing I don't get: Why is database stuff defined in the entities?

http://phpdatamapper.com/docs/entities/

AFAIK, the whole purpose of the data mapper pattern is to separate db stuff from non db stuff:

http://martinfowler.com/eaaCatalog/dataMapper.html

**Comment by marcelloh** [comment]
It has a use:
- when you create a database from within the ORM
- when you want the fields for a new record filled with default 'dynamic' values

You can always write a routine that reads this out of the database ;-)

Anyway: I agree with Martin Fowler, but then you loose some of the advantages we now have.

**Comment by vlucas** [comment]
This has been answered here: https://github.com/vlucas/spot2/issues/17

**Comment by marcelloh** [comment]
I think the one who asks, is not why it is in the entity, and not in the mapper, but why is there a kind of database configuration inside a php class (is the question behind the question)

**Comment by whatda** [comment]
Ok, I understand. Thanks.
