### ISSUE TITLE
No way to unset data that tainted the Entity

### ISSUE THREAD

**Issue by nebulousGirl** [vlucas/spot2#147]
I have an entity that has a property which is only used for validation. But, Spot complains on insertion because of the strict mode and the property that isn't in fields.

We could have a type that does not get inserted in DB, or we could add a function that allows you to unset a property. What do you think is the best?

**Comment by vlucas** [comment]
Is not using strict mode an option here?

**Comment by nebulousGirl** [comment]
I ended up using `["strict" => false]` as the options parameter

**Comment by marcelloh** [comment]
I made this in a separate option inside the entity:
```
    public static function validationConditions()
    {
        return [
            'name' => ['NotNull' => true, 'HasUpper' => true],
            'shortname' => ['NotNull' => true],
        ];
    }
```
Which is called just before a save (applyanswers) and will not save (but back to edit) when a validation does not match
