### ISSUE TITLE
error HY000]: General error : vendor/vlucas/spot2/lib/Mapper.php (404)

### ISSUE THREAD

**Issue by marcelloh** [vlucas/spot2#151]
This is a kind of snippet of my code:
        $sql = "drop table if exists `test`";
        // delete table
        $mapper = $this->app['spot']->mapper("Entities\\test");
        $result = $mapper->query($sql);

It tries to get a collection in the mapper on line 566, then crashes on 
foreach ($cursor as $data)
since the cursor has no $data

**Comment by FlipEverything** [comment]
Hello!

If you want to delete a table, you can do it by executing: 

```php
$mapper = $this->app['spot']->mapper("Entities\test");
$result = $mapper->dropTable();
```

You don't need to write an SQL statement by hand.

**Comment by marcelloh** [comment]
This could be something for the documentation then, since it is mentioned nowhere.
Thanks for the tip :-)

**Comment by FlipEverything** [comment]
The documentation is rather incomplete but you can figure it out by reading the source or something.

**Comment by FlipEverything** [comment]
The dropTable function is destructive. I think that's the reason behind the lack of documentation. 
If your issue is resolved, you should close this ticket.
