### ISSUE TITLE
final sql statement

### ISSUE THREAD

**Issue by marcelloh** [vlucas/spot2#152]
Since I can't find it in the docs, is there some function to see what query is finally run?
I tried to debug the mapper, and can only see the one without the parameters filled in.
Or are the logged somewhere, so I can call them at the end of my page building process?

**Comment by tuupola** [comment]
I use an custom [MonologSQLLogger](https://gist.github.com/tuupola/03a5bc0cea694b972b58) for DBAL to log all queries Spot makes.

**Comment by marcelloh** [comment]
I use monolog too, but how/where do you configure that in Spot ORM?

**Comment by tuupola** [comment]
Check the [usage.php](https://gist.github.com/tuupola/03a5bc0cea694b972b58#file-usage-php) in the Gist for example configuration.
