### ISSUE TITLE
hasOne vs BelongsTo

### ISSUE THREAD

**Issue by marcelloh** [vlucas/spot2#158]
I took the advice and changed my belongsTo into a hasOne

inside my client-entity:

```

 public static function fields()
    {
        return [
            'id'                        => ['type' => 'integer', 'primary' => true, 'autoincrement' => true],
            ...some more fields...
            'country_id'                => ['type'  => 'integer'],
            'crmdepartment_id'          => ['type'  => 'integer'],
            'name'                      => ['type'  => 'string'],
            'user1_id'                  => ['type'  => 'integer'],
            'user2_id'                  => ['type'  => 'integer'],
            ...some more fields...
            ];
    }

```
And these are my relations:

```
    public static function relations(\Spot\MapperInterface $mapper, \Spot\EntityInterface $entity)
    {
        return [
            'country' => $mapper->hasOne($entity, 'Entities\Country', 'country_id'),
            'department' => $mapper->hasOne($entity, 'Entities\Department', 'crmdepartment_id'),
            'crmuser1' => $mapper->hasOne($entity, 'Entities\Crmuser', 'user1_id'),
            'crmuser2' => $mapper->hasOne($entity, 'Entities\Crmuser', 'user2_id'),
        ];
    }


```
Everything was a belongsTo and was working fine.
Now I have the hasOne... and it is broken.
I get and sql error and these are the 2 slq commands when I debug:
```
SELECT * FROM `client` `client` WHERE `client`.`crmdeletedby_id` = ? AND `client`.`crmdepartment_id` >= ? AND `client`.`clientstatus` = ? ORDER BY `client`.`name` ASC LIMIT 15 OFFSET 0 (Params: 0,0,100)
SELECT * FROM `crmdepartment` `crmdepartment` WHERE `crmdepartment`.`crmdepartment_id` IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) (Params: 1,2,623,803,231,593,256,665,594,241,230,1153,1152,237,952)
```
What I see, is that with the 2nd query, it takes the wrong field, because it should be 'id' and not 'crmdepartment_id'.

Perhaps I still don't know the difference in belongsTo and hasOne, or I don't understand how it works.

**Comment by vlucas** [comment]
Check the primary key in the `Entities\Department` class - I think that is what is breaking in this query.

**Comment by vlucas** [comment]
You should also probably set indexes on the relation fields:

```
            'country_id'                => ['type'  => 'integer', 'index' => true],
            'crmdepartment_id'          => ['type'  => 'integer', 'index' => true],
            // etc...
```

**Comment by marcelloh** [comment]
I can't find anything wrong with the depart entity:
```
public static function fields()
    {
        return [
            'id'               => ['type' => 'integer', 'primary' => true, 'autoincrement' => true],
            'name'             => ['type' => 'string', 'required' => true],
            'shortname'        => ['type' => 'string', 'required' => true],
            'crmcreatedby_id'  => ['type' => 'integer', 'required' => true],
            'crmcreatedon'     => ['type' => 'datetime', 'value' => new \DateTime()],
            'crmdeletedby_id'  => ['type' => 'integer', 'required' => true],
            'crmdeletedon'     => ['type' => 'datetime', 'value' => new \DateTime()],
            'crmmodifiedby_id' => ['type' => 'integer', 'required' => true],
            'crmmodifiedon'    => ['type' => 'datetime', 'value' => new \DateTime()]
        ];
    }
}
```

I did try it again just now, with the ['type'  => 'integer', 'index' => true], as you suggested, but it still used the wrong fieldname as id:
```
An exception occurred while executing 'SELECT * FROM `crmdepartment` `crmdepartment` WHERE `crmdepartment`.`crmdepartment_id` IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)' with params [767, 637, 638, 639, 640, 641, 755, 642, 766, 945, 643, 762, 757, 644, 1156, 645, 769, 761, 949, 646, 647, 648, 649, 756, 650, 948, 906, 651, 652, 944, 942, 745, 943]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'crmdepartment.crmdepartment_id' in 'where clause'
```

**Comment by vlucas** [comment]
Let me see the `relations` for both entities please.

**Comment by marcelloh** [comment]
the department entity has no relations.
I think I follow the example in the documentation. There I don't see a relation at the user entity which refers to the post entity. Perhaps I am mistaken, so enlighten me.

**Comment by nebulousGirl** [comment]
Also, the actual code triggering the exception would be useful. How do you query your data using Spot?

**Comment by marcelloh** [comment]
// relations from client-entity
(and if I change the hasOne back to belongsTo, it works)
```

public static function relations(\Spot\MapperInterface $mapper, \Spot\EntityInterface $entity)
{
        return [
            'country' => $mapper->belongsTo($entity, 'Entities\Country', 'country_id'),
            'department' => $mapper->hasOne($entity, 'Entities\Department', 'crmdepartment_id'),
            'crmuser1' => $mapper->belongsTo($entity, 'Entities\Crmuser', 'user1_id'),
            'crmuser2' => $mapper->belongsTo($entity, 'Entities\Crmuser', 'user2_id'),
        ];
}
```

// the part from client-handling-class
```
$mapper = $this->app['spot']->mapper('Entities\\Client');
$dataRecords = $mapper->getAllApiRecords();
$result = json_encode($dataRecords);
```

// the part from client-mapper
```
public function getAllApiRecords()
{
        $result = $this->all()
            ->with(['department', 'country'])
            ->order(['name' => 'ASC']);

        return $result->toArray();
    }
```
// the actual error

`
File: /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php (71)
`

// the sql error
```
An exception occurred while executing 'SELECT * FROM `crmdepartment` `crmdepartment` WHERE `crmdepartment`.`crmdepartment_id` IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)' with params [767, 637, 638, 639, 640, 641, 755, 642, 766, 945, 643, 762, 757, 644, 1156, 645, 769, 761, 949, 646, 647, 648, 649, 756, 650, 948, 906, 651, 652, 944, 942, 745, 943]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'crmdepartment.crmdepartment_id' in 'where clause'
```

**Comment by nebulousGirl** [comment]
The difference between a BelongsTo and HasOne relation is the location of the linking column.

In a BelongsTo relation, you have a column on your table which references a column on another (usually the primary key).

A HasOne (or a HasMany) relation is the direct opposite of a BelongsTo. Your table does not have the relation column. It is the related table that has the column referencing the primary key in your table.

So in your case, I think that you should be using BelongsTo relations for all your relations.

You could optionally define the reverse relations in your other entities. Your country can have a HasMany relation for clients if you need it.

**Comment by marcelloh** [comment]
The thing is, that I am doing just that, but when I read back, I see some different comments about the usage. (but then again: that just gives me errors)

**Comment by tuupola** [comment]
If you are referring #154 you were shown how that instead of using `->with()` you can access relations using following example code.

```php
$user =  $spot->mapper("User")->get(1);
print_r($user->profile);
```

At no point you have been suggested to use `hasOne`.

**Comment by marcelloh** [comment]
A client can belongTo 1 department, or should I say, a client hasOne department
(or country... or whatsoever)

If a client hasOne otherthing, and the releationship should be something like this:
'department' => $mapper->hasOne($entity, 'Entities\Department', 'id'),
I assume, the department.id is used in the last var.
But then,to which field this is matched in client?
I think, nebulousGirl tried to tell me, that auto-magically, when there is a column called "client_id", this will work? (and which rules are there for that special field?)
I find that wierd to imagine because more clients have the same department....
Still I can't figure out from the docs, and from what you try to tell me, how this should work.
But if you all get tired of me. Sorry, then stop explaining.

**Comment by nebulousGirl** [comment]
I will write a more concrete explanation. First, let's describe all possible relations for the Client and Department entities:

```php

//Entities\Client
 public static function fields()
    {
        return [
            'id'                        => ['type' => 'integer', 'primary' => true, 'autoincrement' => true],
            ...some more fields...
            'country_id'                => ['type'  => 'integer'],
            'crmdepartment_id'          => ['type'  => 'integer'],
            'name'                      => ['type'  => 'string'],
            'user1_id'                  => ['type'  => 'integer'],
            'user2_id'                  => ['type'  => 'integer'],
            ...some more fields...
            ];
    }

    public static function relations(\Spot\MapperInterface $mapper, \Spot\EntityInterface $entity)
    {
        return [
            'country' => $mapper->belongsTo($entity, 'Entities\Country', 'country_id'),
            'department' => $mapper->belongsTo($entity, 'Entities\Department', 'crmdepartment_id'),
            'crmuser1' => $mapper->belongsTo($entity, 'Entities\Crmuser', 'user1_id'),
            'crmuser2' => $mapper->belongsTo($entity, 'Entities\Crmuser', 'user2_id'),
        ];
    }

//Entities\Department
public static function fields()
    {
        return [
            'id'               => ['type' => 'integer', 'primary' => true, 'autoincrement' => true],
            'name'             => ['type' => 'string', 'required' => true],
            'shortname'        => ['type' => 'string', 'required' => true],
            'crmcreatedby_id'  => ['type' => 'integer', 'required' => true],
            'crmcreatedon'     => ['type' => 'datetime', 'value' => new \DateTime()],
            'crmdeletedby_id'  => ['type' => 'integer', 'required' => true],
            'crmdeletedon'     => ['type' => 'datetime', 'value' => new \DateTime()],
            'crmmodifiedby_id' => ['type' => 'integer', 'required' => true],
            'crmmodifiedon'    => ['type' => 'datetime', 'value' => new \DateTime()]
        ];
    }
}
    public static function relations(\Spot\MapperInterface $mapper, \Spot\EntityInterface $entity)
    {
        return [
            'clients' => $mapper->hasMany($entity, 'Entities\Client', 'crmdepartment_id'),
            'crmcreatedby' => $mapper->belongsTo($entity, 'Entities\Crmuser', 'crmcreatedby_id'),
            'crmdeletedby' => $mapper->belongsTo($entity, 'Entities\Crmuser', 'crmdeletedby_id'),
            'crmmodifiedby' => $mapper->belongsTo($entity, 'Entities\Department', 'crmmodifiedby_id'),
        ];
    }

The one thing all belongsTo relations have in common is that the field you write as a third argument is on the entity itself. While for hasOne or hasMany relations, the third argument is a field on the related entity.

So, as a rule to help you not confuse hasOne and belongsTo relations is to ask yourself if the field linking the 2 entities is on current entity (belongsTo) or on the related entity (hasOne).

So on your Client entity, you are linking to a department using the department_id field on your Client entity. You need a BelongsTo relation. If you had a client_id on the Department entity, you would need to define a hasOne relation on your Client entity instead because the linking field is not on the Client entity.

**Comment by marcelloh** [comment]
Ok, thank you very much. I figured out, from all that I've learned so far:

a hasOne is only used in a 1-1 relationship
- the key in the configured relation is the key of the relational-entity
- the key inside the relational-entity must be in the form of entityname_id

a belongsTo is used in a N-1 relationship
- the key in the configured relation is the field in this entity
- the relation is coupled via the id field inside the relational-entity

and please, let this be correct :-)

**Comment by nebulousGirl** [comment]
Yes, that's about it, except that a belongsTo can also be used in either a 1-1 or N-1 relationship:

```php
//User
public function fields()
{
    return [
        'id' => ['type' => 'integer'],
        'profile_id' => ['type' => 'integer'],
    ]
}
public function relations()
{
    return [
        'profile' => $mapper->belongsTo($entity, 'Profile', 'profile_id')
    ];
}
//Profile
public function fields()
{
    return [
        'id' => ['type' => 'integer'],
        'photo' => ['type' => 'string'],
    ]
}
public function relations()
{
    return [
        'user' => $mapper->hasOne($entity, 'User', 'profile_id')
    ];
}
```
Just a small note about "entityname_id", it is not mandatory to use this form, but a best practice to make the relation obvious when looking directly at the database.

**Comment by vlucas** [comment]
@nebulousGirl thanks for the great explanation and detail here.

@marcelloh Just wanted to clarify one thing that @nebulousGirl touched on.

> the key inside the relational-entity must be in the form of entityname_id

There is absolutely **NO MAGIC** in Spot 2. The query will use whatever column name you give it when defining the relation. That could be something sane and readable like `entityname_id` (which is widely considered best practice), or it could be something completely nonsensical like `someThing573`. _Spot doesn't make any assumptions about your database structure AT ALL_. The only thing the relations do is lookup the defined primary key field on the target entity and use that for queries - the column name is not guessed at all. Hope that clears a few things up here :)

**Comment by marcelloh** [comment]
Thanks for your patience and the explanations so far. I somehow hope this will make it into the documentation in some form.
