### ISSUE TITLE
Complex Queries Using Custom SQL gives error

### ISSUE THREAD

**Issue by marcelloh** [vlucas/spot2#171]
As I am into migrations these days, I have the following:
A valid insert SQL statement read into memory (in var: $sql)
```
INSERT INTO `users` (`id`, `email`, `login`, `name`, `password`, `role_id`, `appdepartment_id`, `appcreatedby_id`, `appcreatedon`, `appdeletedby_id`, `appdeletedon`, `appmodifiedby_id`, `appmodifiedon`) VALUES
                    (1,     '',       '', '*** Unknown ***', '',    NULL,      NULL,     1, '0000-01-01 00:00:00', 0, '0000-01-01 00:00:00', 0, '0000-01-01 00:00:00');
```

and the following command:
$result = $usermapper->query($sql);

The strange thing is, that the statement is really executed and is visible in the database.
but... it ends with:
```
 [PDOException]  SQLSTATE[HY000]: General error 
```

So that last thing is unexpected.

**Comment by tuupola** [comment]
IIRC you get that error from PDO if you try to fetch an `INSERT` query. Without looking at the code I am pretty sure Spot assumes you are using complex queries only to `SELECT` data.

**Comment by marcelloh** [comment]
I think so too, but you know what they say about assumptions....
I would rather read it somewhere to be sure.
And then again: why would an ORM only support custom select queries only?

**Comment by tuupola** [comment]
http://doctrine-orm.readthedocs.io/projects/doctrine-dbal/en/latest/reference/data-retrieval-and-manipulation.html

> executeQuery($sql, $params, $types) - Create a prepared statement for the passed SQL query, bind the given params with their binding types and execute the query. This method returns the executed prepared statement for iteration and is useful for SELECT statements.

If you want to write your SQL manually why use ORM?

**Comment by marcelloh** [comment]
I need to write it manually, since mapper->droptable() (as example) does not work
and also... I want to be able to have a part of the data inserted when I start the application for the first time. And yes, I could write a lot of ORM insert statements, but I rather take a regular dump, and use that as a base.

What I found (but didn't test it yet, is that Doctrine has this executeQuery() that could possibly handle inserts.... but I'm not using Doctrine, but Spot ORM

I know that Doctrine has the option to work with native sql (and therefore with inserts etc), but not sure how to call that from within my mapper object.

**Comment by tuupola** [comment]
Spot uses Doctrine DBAL internally. Looking at the [source](https://github.com/vlucas/spot2/blob/master/lib/Mapper.php#L563-L571) it seems you can access the DBAL connection with `$mapper->connection()` which most likely means you can do stuff like `$mapper->connection()->executeQuery(...)` or `$mapper->connection()->insert(...)` manually.

**Comment by marcelloh** [comment]
This is good news, because this works :-)
Perhaps a good thing to get this in the section "Complex Queries" :-)
Thanks...

**Comment by vlucas** [comment]
Good idea - glad you got this working. The docs definitely need to be updated.

**Comment by vlucas** [comment]
It also seems like a good thing to expose an `exec` method to allow you to run arbitrary queries as well. That will be added to the next release. I know all these little papercuts are frustrating, @marcelloh - but hang in there! All your issue reports help us make Spot better for the next release! :)

**Comment by marcelloh** [comment]
Please don't see it that I am frustrated, which I am not :-) I always find it typical, that somehow I can easily tip the edged of a nice piece of software, and sometimes come to the conclusion that I am sometimes falling over the edge ;-)
Luckily, I am not doing this in production yet, but  it will be soon.
