### ISSUE TITLE
Spot2 transaction

### ISSUE THREAD

**Issue by StephanKrauss** [vlucas/spot2#176]
Hello,

i'm a beginner in working with spot orm.
I need a simple example how can i work with transaction in spot2.

How can help ?

Your sincerly

Stephan

**Comment by sorinstanila** [comment]
Hi, 
You can use 
$mapper->connection()->beginTransaction() 
where $mapper is instanceof/extends Mapper

**Comment by vlucas** [comment]
There is a built-in `transaction` method:

```php
$mapper->transaction(function() use($mapper) {
    // ... your queries
});
```

The `transaction` will auto-commit by default, and will rollback if you throw an Exception or `return false` from within the closure.

**Comment by marcelloh** [comment]
I think, this can be closed if the documentation is in order.

**Comment by esclkm** [comment]
/v1/portals/{portals}/sites/{code}/products/availability
