### ISSUE TITLE
how to use like

### ISSUE THREAD

**Issue by marcelloh** [vlucas/spot2#179]
lets say I want all entities with a name like '%candy%'
How would I do that?

**Comment by vlucas** [comment]
You just put the wildcard characters in the value:

```php
        $query = $mapper->where(['title :like' => '%lorem%', 'status >=' => 1])->toSql();
```

**Comment by marcelloh** [comment]
Thanks :-) a tried a lot of different things, but this one I skipped hahaha... 
But ehm, I want this to be in the documentation, and when you're ok with it, I would like to make a page with Special tips and tricks, just for these kind of things.
