### ISSUE TITLE
Is it possible to filter related entities?

### ISSUE THREAD

**Issue by stojanovic-nikola** [vlucas/spot2#186]
When using ->with(), is there a way to set conditions?

I have a case of multilanguage site and would like to query only rows with specific LanguageId.

``` $events = $mapper->all()->with('EventDescriptions') ``` would return all descriptions, and it would be nice in this case to select only those where event_descriptions.LanguageId matches some value.

**Comment by tuupola** [comment]
The `->with()` method is not used for defining relations. It is used for eager loading. You can define filtered relations in the same way as normal relations. For example something like:

```php
public static function relations(MapperInterface $mapper, EntityInterface $entity)
{
    return [
        "english" => $mapper
                        ->hasMany($entity, "Message", "parent_id")
                        ->where(["language" => "en"]),
        "estonian" => $mapper
                        ->hasMany($entity, "Message", "parent_id")
                        ->where(["language" => "et")
    ];
}
```

**Comment by stojanovic-nikola** [comment]
Thanks

**Comment by vlucas** [comment]
You should also be able to chain additional query conditions on the relation itself before you loop over it or `count()` it.

```php
$events = $mapper->all();
foreach($events as $event) {
    // You can also add query conditions here if they are not eager loaded, but be careful of the N+1 dragons...
    $event->relation->where(['language' => 'en']);
}
```
