### ISSUE TITLE
Prefix tables

### ISSUE THREAD

**Issue by Biromain** [vlucas/spot2#188]
Sorry, i search a way to define tables prefix dynamically for each connection.
Any idea to doing that properly?

Regards,

**Comment by nebulousGirl** [comment]
I would take a look at overriding the `Query\Resolver`. To use your new Resolver, you need to extend the `Mapper` and override the `resolver` method. Also, I think you would also need to override the `table` to add your prefix.

**Comment by Biromain** [comment]
I just made an Base Entity inherited by all and just override table method (mode getter) and that seem to work.
