### ISSUE TITLE
get -> with (a.k.a. Why doesn't get have the with-option?)

### ISSUE THREAD

**Issue by marcelloh** [vlucas/spot2#206]
I am trying:
`
$result = $this->get($id)->with('relationtable');
`
the workaround I have:
`
$result = $this->where(['id' =>$id])->with('relationtable');
`
But it gives me an array with 1 record, where the other option gives me an array with record-fields
Why doesn't get have the with-option?

**Comment by vlucas** [comment]
You can use this to get a single record:

```php
$result = $this->where(['id' =>$id])->with('relationtable')->first();
```

The `get` method will always return a single entity immediately.
