### ISSUE TITLE
how to do this in spot orm (multiple and/or)

### ISSUE THREAD

**Issue by marcelloh** [vlucas/spot2#209]
SELECT * FROM posts
WHERE (status = 'published' OR WHERE status = 'draft')
AND (year = 2016 OR year =2015)
AND (....)

I try to find it in the documentation, or figure out doing it in the software... but it's unclear to me for now.

**Comment by FlipEverything** [comment]
I think you can do something like this, right? Somebody correct me If I'm wrong.

```php
$mapper -> $spot->mapper('Entity\Posts');
$posts = $mapper->where('status IN' => ['published', 'draft'], 'year IN' => ['2016', '2016']);
```

**Comment by marcelloh** [comment]
Sound like a very good solution :-)
I was stuck in where/andwhere/orwhere kind of things so I didn't see the obvious.
