### ISSUE TITLE
save and update functions are not define properly.

### ISSUE THREAD

**Issue by flik** [vlucas/spot2#211]
save and update functions are not define properly. We face lot of issues in save and update in mostly frameworks.

**Comment by tuupola** [comment]
How they are not defined properly and what issues you have?

**Comment by flik** [comment]
You have defined Migration, Find, Custom query, relation, but I could not find anything in the readme related insert update. Mostly we stuck here in any framework. Here is example: https://laravel.com/docs/5.3/eloquent#inserting-and-updating-models

In this way you should told and also without joins life is miserable.

**Comment by tuupola** [comment]
http://phpdatamapper.com/docs/crud/

**Comment by FlipEverything** [comment]
I can +1 @tuupola 
You should read the documentation! If your issue is resolved, please close this thread.
