### ISSUE TITLE
Group where and orWhere

### ISSUE THREAD

**Issue by keevitaja** [vlucas/spot2#218]
Hello,

is it possible to group where and orWhere without using raw queries?

`where a = 1 and (where b = 8 or where c = 4)`

**Comment by Arzaroth** [comment]
You can achieve this doing :
```php
$mapper->where(['a' => 1])->andWhere(['b' => 8, 'c' => 4], 'OR');
```

**Comment by Kipperlenny** [comment]
Any solution for:

`where a = 1 and (where b LIKE "8 %" or where b LIKE "% 8 %")`

?

**Comment by FlipEverything** [comment]
```php
$mapper->where(['a' => 1])->andWhere(['b :like' => '8 %', 'b :like' => '% 8 %'], 'OR');
```

**Comment by Kipperlenny** [comment]
Are you sure? An array with the same key twice?

**Comment by FlipEverything** [comment]
Sorry, my bad... You can try this workaround:

### Example code:
```php
$query = $mapper->select()->noQuote()->where(['name' => 1])->andWhere(['email :like' => '8 %', 'email  :like' => '% 8 %'], 'OR');
echo($query->toSql()).PHP_EOL;
var_dump($query->getParameters());
```
### Output:
```php
SELECT * FROM x WHERE (x.name = ?) AND (x.email LIKE ? OR x.email LIKE ?)
array(3) {
  [1] =>
  int(1)
  [2] =>
  string(3) "8 %"
  [3] =>
  string(5) "% 8 %"
}
```

Ofc you can restructure your request or do a regex instead etc.

**Comment by Kipperlenny** [comment]
Thank you very much!
I used another option: created my own operator.
