### ISSUE TITLE
Convert empty string to null with eventMitter

### ISSUE THREAD

**Issue by Sysix** [vlucas/spot2#219]
Hey guys, I tried so check my data before saving it into the database.
I found that the Mapper has access to an Listener with callback-functions.

My code:

```php
<?php

namespace AddOn\Library\Model;


use Core\Sql\DataObject;
use Spot\EntityInterface;
use Spot\MapperInterface;

class PackageTag extends DataObject // extends Entity
{
    protected static $table = 'package_tags';

    public function getMapper()
    {
        $mapper = parent::getMapper();

        $mapper->eventEmitter()->on('beforeSave', [$this, 'checkParentForEmpty']);

        return $mapper;
    }

    public function checkParentForEmpty(&$tag)
    {
        if ($tag->parent === '') {
            $tag->parent = null;
        }

        return true;
    }

    public function getRootTags()
    {
        return $this->getMapper()->all()->where(['parent' => null]);
    }

    public static function fields()
    {
        return [
            'tag' => [
                'type' => 'string',
                'length' => 255,
                'primary' => true,
            ],
            'parent' => [
                'type' => 'string',
                'length' => 255,
                'index' => true,
                'default' => null
            ]
        ];
    }

    public static function relations(MapperInterface $mapper, EntityInterface $entity)
    {
        return [
            'children' => $mapper->hasMany($entity, __CLASS__, 'parent'),
            'parent' => $mapper->belongsTo($entity, __CLASS__, 'parent')
        ];
    }
}
```

With XDebug I found, that on `EventEmitterTrait:emit` the result of the callback is always "null".

What is with the code wrong?

**Comment by nebulousGirl** [comment]
It shouldn't be possible that it returns null. 

See the class used for events: https://github.com/fruux/sabre-event/blob/master/lib/EmitterTrait.php

You don't need the "&" beside $tag either, PHP objects are references by default.

**Comment by Sysix** [comment]
> You don't need the "&" beside $tag either, PHP objects are references by default.
Yeah I know, but for help to understand, that the object is changing. 

> It shouldn't be possible that it returns null.
I dont see a condition, which check for null. Only for false

**Comment by tuupola** [comment]
The way you use events looks a bit unorthdox. Have you tried the [documented way](http://phpdatamapper.com/docs/events/)? Ie. something like:

```php
public static function events(EventEmitter $eventEmitter)
{
    $eventEmitter->on('beforeSave', function (Entity $entity, Mapper $mapper) {
          /* checkParentForEmpty logic here, returning false cancels saving */
    });
}
```

**Comment by Sysix** [comment]
I found the problem. It was really the Problem with the reference. 
The Error-Message was not shown. After I `die()` in the callback, I could debugging :)

Thanks for the help!
