### ISSUE TITLE
Check if relation exists with existing model

### ISSUE THREAD

**Issue by Sysix** [vlucas/spot2#222]
Hello Guys,

I'm back with a new question ;)

My Setup:

- I have 3 Models (`User`, `UserPerm` and `UserPermRelation`)
- All 3 Models has relations with each other (N to N)
- `User`-Model as initial no Relation set (`$mapper->first(['id' => 1]);`)

**UserPermRelation** (I hope that the Relation is enough Information for my Problem)
```php
 public static function fields()
    {
        return [
            'user_id' => [
                'type' => 'integer',
                'length' => 80,
                'primary' => true,
                'required' => true,
            ],
            'perm_id' => [
                'type' => 'integer',
                'length' => 80,
                'primary' => true,
                'required' => true,
            ]
        ];
    }

    public static function relations(MapperInterface $mapper, EntityInterface $entity)
    {
        return [
            'users' => $mapper->hasMany($entity, '\\AddOn\\Login\\Model\\User', 'id', 'user_id'),
            'perms' => $mapper->hasMany($entity, '\\AddOn\\Login\\Model\\UserPerm', 'id', 'perm_id')
        ];
    }
```

Now I want to add on my `User`-Model a Method called `$user->hasPerm($perm)`
How do I solve this? I found example like #186 but it not works like I thought.

Thanks for your help!

**Comment by nebulousGirl** [comment]
I think you should be able to do it with relation/get method in your model.

    public function hasPerm($perm)
    {
        $perms = $this->relation('perms'); //returns HasManyRelation object
        if ($perms === false) {
            //Relation is not loaded
        }
        //logic to check if user has perm
        foreach ($perms as $userPerm) {
            //...
        }
        return false; //or whatever
    }

**Comment by Sysix** [comment]
Thanks ;) I thought that could be done easier without an foreach loop.
