### ISSUE TITLE
Access to pivot data with Relation::HasManyThrough()

### ISSUE THREAD

**Issue by tuupola** [vlucas/spot2#35]
There are cases when you want to store extra data in the pivot table used by `Relation::HasManyThrough()`. For example you have many shops and many products. One shop can have multiple products. One product might be sold in multiple shops. However each shop might have different price. Important parts of code would be something like:

```php
/* Product.php */
public static function relations(MapperInterface $mapper, EntityInterface $entity) {
    return [
        "shops" => $mapper->hasManyThrough($entity, "Shop", "Stock", "shop_id", "product_id")
    ];
}
```
```php
/* Shop.php */
public static function relations(MapperInterface $mapper, EntityInterface $entity) {
    return [
        "products" => $mapper->hasManyThrough($entity, "Product", "Stock", "product_id", "shop_id")
    ];
}
```
```php
/* Stock.php */
public static function fields() {
    return [
        "id" => ["type" => "integer", "primary" => true, "autoincrement" => true],
        "product_id" => ["type" => "integer", "unsigned" => true, "unique" => "shop_product", "required" => true],
        "shop_id" => ["type" => "integer", "unsigned" => true, "unique" => "shop_product", "required" => true],
        "price" => ["type" => "decimal", "precision" => 10, "scale" => 2]
    ];
}
```

The problem is you cannot access the price. Ideally I would like to do something like:

```php
$shop = $spot->mapper("Shop")->get(1);
foreach ($shop->products as $product) {
    var_dump($product->stock->price);
}
```

I can think of several ways of doing this. Easiest is to give hardcoded name for pivot data. For example `pivot`.  You would then access it with `$product->pivot->price`. Generally I do not like hardcoded variable names. So maybe no.

Another option is to use magic and derive the name from through entity: `strtolower($throughEntity)`. This also probably is not good. Does not work well with namespaced entity names. Too much magic is bad. 

Best option I can think of is to give the name for pivot data as parameter. This way developers can choose the naming by themselves.

```php
"products" => $mapper->hasManyThrough($entity, "Product", "Stock", "product_id", "shop_id", "inventory")
```

```php
$shop = $spot->mapper("Shop")->get(1);
foreach ($shop->products as $product) {
    var_dump($product->inventory->price);
}
```

What do you think?

**Comment by Euregan** [comment]
Hello, I'm quite in the same case as you, did you find any elegant solution ?

**Comment by tuupola** [comment]
Nothing elegant. I just ended up querying inserting the stock manually when needed. Since the project is low volume this was Good Enough (tm) .

```php
foreach ($shop->products as $product) {
     $product->stock = $app->spot->mapper("Stock")
         ->first(["product_id" => $product->id, "shop_id" => $shop->id]);
}
```

After reading a [bit more](http://paul-m-jones.com/archives/6068) about it correct term is `association table`. There is a popular ORM which uses `pivot table` incorrectly and got me confused.

That said I am not sure anymore if what I described above is good idea. When you put extra columns to association table it becomes an actual entity so maybe it should be treated like one. Instead of shop having products which have stock think of it as shop which has stocks which has a product.

```php
/* Product.php */
public static function relations(MapperInterface $mapper, EntityInterface $entity) {
    return [
         "stocks" => $mapper->hasMany($entity, "Stock", "product_id")
    ];
}
```
```php
/* Shop.php */
public static function relations(MapperInterface $mapper, EntityInterface $entity) {
    return [
         "stocks" => $mapper->hasMany($entity, "Stock", "shop_id")
    ];
}
```
```php
/* Stock.php */
public static function fields() {
    return [
        "id"       => ["type" => "integer", "primary" => true, "autoincrement" => true],
        "product_id" => ["type" => "integer", "unsigned" => true],
        "shop_id"  => ["type" => "integer", "unsigned" => true],
        "price"    => ["type" => "decimal", "precision" => 10, "scale" => 2]
   ];
}

public static function relations(MapperInterface $mapper, EntityInterface $entity) {
    return [
        "shop" => $mapper->belongsTo($entity, "Shop",  "shop_id"),
        "product" => $mapper->belongsTo($entity, "Product",  "product_id"),
    ];
}
```

Now we can access shop product and their prices:

```php
$shop = $spot->mapper("Shop")->get(2);
foreach ($shop->stocks as $stock) {
    print "{$stock->product->name} : {$stock->price} \n";
}
```

To avoid N+1 problem loop can be done like this:

```php
foreach ($shop->stocks->with("product")  as $stock) {
    print "{$stock->product->name} : {$stock->price} \n";
}
```

I find this much more elegant than my original suggestion. It also fits better to Datamapper pattern. Datamapper users usually prefer control over magic.

**Comment by Euregan** [comment]
It is, but if there is no plan to support stock, then the Stock entity becomes redundant and adds complexity to the code, when it would be much simpler to have everything in the Product, while still having separate tables for redundance reasons.
I'll stick with your first solution, thanks for sharing :D

**Comment by tuupola** [comment]
If you add something to association table then it becomes an entity anyway. What the entity is called is not relevant. 

I am sure eager loading works. I can see it from the [query logs](https://gist.github.com/tuupola/03a5bc0cea694b972b58). In the tests I had product table with three products only, but you can already see the difference.

With eager loading
```
[2015-03-07 20:04:27] [DEBUG]: SELECT * FROM shops shops WHERE `shops`.`id` = '2' LIMIT 1 -- 0.00070405006408691
[2015-03-07 20:04:27] [DEBUG]: SELECT * FROM stocks stocks WHERE `stocks`.`shop_id` = '2' -- 0.00027298927307129
[2015-03-07 20:04:27] [DEBUG]: SELECT * FROM products products WHERE `products`.`id` IN ('1','2','3') -- 0.00030994415283203
```
Without eager loading
```
[2015-03-07 20:04:55] [DEBUG]: SELECT * FROM shops shops WHERE `shops`.`id` = '2' LIMIT 1 -- 0.0014710426330566
[2015-03-07 20:04:55] [DEBUG]: SELECT * FROM stocks stocks WHERE `stocks`.`shop_id` = '2' -- 0.00038790702819824
[2015-03-07 20:04:55] [DEBUG]: SELECT * FROM products products WHERE `products`.`id` = '1' -- 0.00021910667419434
[2015-03-07 20:04:55] [DEBUG]: SELECT * FROM products products WHERE `products`.`id` = '2' -- 0.00017809867858887
[2015-03-07 20:04:55] [DEBUG]: SELECT * FROM products products WHERE `products`.`id` = '3' -- 0.00032806396484375
```

**Comment by Euregan** [comment]
Okay, thanks for your answer :D
