### ISSUE TITLE
Question about Collection::merge

### ISSUE THREAD

**Issue by aspyatkin** [vlucas/spot2#57]
Hello!
I have encountered some problem while using Spot2. Here's a small snippet
```php
// Document is some model
$mapper = Mapper::get('Document');
$documents = $mapper->all()->where(['user_id' => 1]);
$documents->merge($mapper->all()->where(['user_id' => 2])); // Exception!

foreach($documents as $document) {
    // ...
}
```

I supposed that it would get all the documents for users 1 and 2. But unfortunately, it threw an exception:
`PHP Catchable fatal error:  Argument 1 passed to Spot\Entity\Collection::merge() must be an instance of Spot\Entity\Collection, instance of Spot\Query given`

I know that `where` uses lazy loading, and I should use `execute` at the end of the each query, but ... is there any chance that Spot2 will understand those situations? Ideally, in the snippet above it should evaluate only when it reaches `foreach` block.

**Comment by vlucas** [comment]
Currently Spot2 Collection::merge always expects another collection. To make this work, some type of deferred behavior would have to be added that would get executed on iteration. There are no current plans for that at the moment, but I am not opposed to it.

Something like:
```php
$mapper = Mapper::get('Document');
$documents = $mapper->all()->where(['user_id' => 1]);
$documents->queue(function($collection) {
    $collection2 = $mapper->all()->where(['user_id' => 2])->execute();
    if ($collection2) {
        $documents->merge($collection2);
    }
});
```

Also - I know you may have just given a simple example and this may not be your actual use-case, but you can also add it to the initial query to get it all in one step:
```php
$mapper = Mapper::get('Document');
$documents = $mapper->where(['user_id' => [1, 2]]);
```

**Comment by aspyatkin** [comment]
OK, thank you for explanation.
