### ISSUE TITLE
Not equal operator with empty array

### ISSUE THREAD

**Issue by aspyatkin** [vlucas/spot2#58]
Hello!
I recently was making a lot of work with Spot2. I really appreciate the lightweight syntax, because I need to query database a lot SQL `IN (...)`, `NOT IN (...)`.

Imagine a model (Entity) has some fields with `tag_id` field, that cannot be null.
For example, I have the following code:
``` php
$entities = $entityMapper->where('tag_id !=' => $unneededTagIds);
```
That works great, generating query (for example)
``` sql
SELECT * FROM entities WHERE tag_id NOT IN (1,2,3);
```

But, sometimes I have an empty array of unneeded tags. And when it occurs, Spot2 makes the next query
``` sql
SELECT * FROM entities WHERE tag_id IS NULL;
```
I suppose, that is not you may expected. It will fetch 0 records, regardless of the original intent - to fetch all records with tag_id's not contained in specified array. I think the proper query in that specific case would be
``` sql
SELECT * FROM entities WHERE tag_id IS NOT NULL;
```
I use MySQL, but as far as I know `IS NULL` and `IS NOT NULL` is not vendor-specific.

As I can see, the error can be fixed in `\Spot\Query.php` file, method `parseWhereToSQLFragments`, line, the `if` block starting at line 331. 

**UPD** @vlucas, If you want, I can fork and fix it.

**Comment by vlucas** [comment]
Yes, is should be `IS NOT NULL` in that case - good catch. I had to make an empty array translate to `IS NULL` instead of `IN()`, which produced an SQL error. If you want to patch it and submit a PR, I'd be happy to merge it and publish a new release so you can use it. Thanks!
