### ISSUE TITLE
Merge with intersecting data sets

### ISSUE THREAD

**Issue by aspyatkin** [vlucas/spot2#60]
Hello!
I have found a problem with `EntityCollection::merge` and have written a failing test (you can place it into `SpotTest\QuerySql` in test suite):
``` php
    public function testMergeIntersecting()
    {
        $mapper = test_spot_mapper('SpotTest\Entity\Tag');

        // Fetch 3 entries
        $tags = $mapper->all()->execute();

        // Fetch one entry which already present in $tags and merge
        $tags->merge($mapper->where(['name' => 'Title 1'])->execute());
        $this->assertEquals(3, $tags->count());
    }
```

The first query returns an array with three entities. Then, the second query returns an array with one entity, and this entity is almost the same as the the one from the first query. Unfortunately, the merged array contains 4 entities, not 3.

I suppose `in_array` method (in `EntityCollection::merge`) won't properly compare entity presence, because every `Entity` has a protected `_objectId` field, which is made with `uniqid` and `spl_object_hash`. I have seen a "todo" in the `merge` method documentation, so, ... is it planned to be fixed soon?

**Comment by vlucas** [comment]
This will be fixed in the next release
