### ISSUE TITLE
Warnings Query Line: 637

### ISSUE THREAD

**Issue by brownrl** [vlucas/spot2#61]
I am getting a ton of warnings in the logs for Query.php Line 637.

It is happening when the first() method is called.

### My Code
```php
$result = $cmapper->where( $filters )->order( [ 'content_date' => 'DESC' ] )->first();
```

### Warning
```
Warning: array_splice() expects parameter 1 to be array, object given in
vendor/vlucas/spot2/lib/Spot/Query.php on line 637
```

$filters in an associative array

**Comment by vlucas** [comment]
This doesn't happen in the tests that have `first` in it, and I am not able to re-produce the issue.

That said, I traced the code, and can definitely see where the error can occur - the variable being passed into `array_splice` could be an instance of `Spot\Entity\Collection`, which has it's own use of `array_splice` internally, so it's not actually even needed in this method at all for the same result to happen. I remove it and just kept the simple `unset` method call, which should resolve your issue.
