### ISSUE TITLE
Escaping the table name on insertion

### ISSUE THREAD

**Issue by Euregan** [vlucas/spot2#73]
I have a table named 'order'. Since it is a reserved keyword, it can be escaped with \` (back quote I think it's called), meaning I can do things like : `CREATE TABLE `\``order`\`` ( ... );`. Thing is, when I try to insert a new entity through Spot, the escaping quotes are not used, and the PDO fails quite terribly :(
Is there any way to override that ? Should I just put `protected static $table = "`\``order`\``";`.

P.S.: I had to tweak the markdown a bit to have backquotes in the code, sorry if it looks weird

Edit: Actually, putting back quotes in $table fails the SELECT :(

**Comment by pedromcno** [comment]
This exact same issue bit me as well, with the "nice" addition that when performing a simple ``$orderMapper->get(1234)`` the resulting query was ``SELECT * FROM Order Order WHERE `Order`.`id` = ? LIMIT 1' with params [1234]`` which means that the query is broken in two different ways.

**Comment by vlucas** [comment]
I agree that this should be done, but this is why I explicitly avoid naming tables and columns with reserved SQL keywords - it's just asking for trouble.

**Comment by vlucas** [comment]
This should be fixed now as of v2.1.7.
