### ISSUE TITLE
Relations question

### ISSUE THREAD

**Issue by ti0rafa** [vlucas/spot2#83]
Hi there,

First of all I really like **spot2**, it's really handy. I would really love to have more examples and use cases on how to put everything together.

I have a question regarding the ```with()``` method, I was trying to do something like this:

``` PHP
$Users = $Spot->mapper('Users');
$User = $Users->first(['id' => 1])->with('someValue');

echo $User->someValue;
```

Is there a way i can use ```first()``` and then access a relationship called someValue?

**Comment by vlucas** [comment]
@ti0rafa Just specify with `with` condition before you call `first()`:

```php
$Users = $Spot->mapper('Users');
$User = $Users->where(['id' => 1])->with('someValue')->first();

echo $User->someValue;
```

**Comment by ti0rafa** [comment]
Thanks for the feedback @vlucas
