### ISSUE TITLE
Quoting identifiers inconsistency

### ISSUE THREAD

**Issue by potfur** [vlucas/spot2#84]
Spot is inconsistent with quoting identifiers.
In different parts of same query identifiers are handled in different way.
E.g. table names in `FROM` part are left without quotes, but table names in `WHERE` are quoted.

**Comment by vlucas** [comment]
I don't want to remove quoting completely. If anything, quoting should be *added* to the areas where it is missing.

**Comment by potfur** [comment]
As long as it's consistent - othwerwise there is no way to handle tables/fields with names as reserved keywords.

**Comment by vlucas** [comment]
If you want to try to tackle adding it everywhere, I will definitely merge your work in. I won't be able to get to it myself for another few weeks with a work deadline and a conference I am speaking at next week.

**Comment by potfur** [comment]
Added quotes in: #86

**Comment by potfur** [comment]
Done in #86
