### ISSUE TITLE
Can't fetch relation via "with" method

### ISSUE THREAD

**Issue by wpterra** [vlucas/spot2#95]
In my controller I'm trying to fetch entity data with related info using "with" method as discribed in readme, but I have a fatal error

```PHP
Error: Call to protected method Spot\\Mapper::with() from context 'Controller\\PostController'"
```
Now I fetch related info by executing relations query like this

```PHP
$comments = $entity->comments->execute()->toArray();
```
and then merge it with entity. It works, but "with" methoв will be much simple and clear

**Comment by vlucas** [comment]
The `with` method is supposed to be called from the `Spot\Query` object, not directly from the mapper. For example:

```php
$mapper->all()->with('comments');
```
